import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import './globals.css';
import { Modal } from '@/components';
import { ModalContextProvider } from '@/contexts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const inter = Inter({ subsets: ['latin'] });

interface Props {
  children: ReactNode;
}

const RootLayout = ({ children }: Props): ReactNode => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalContextProvider>
          {children}
          <Modal />
        </ModalContextProvider>
      </body>
    </html>
  );
};

export default RootLayout;
