import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const inter = Inter({ subsets: ['latin'] });

interface Props {
  children: React.ReactNode;
}

const RootLayout = ({ children }: Props): React.ReactNode => {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
