import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import { Header, Modal, NavbarTop } from '@/components';
import { ModalContextProvider } from '@/contexts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const inter = Inter({ subsets: ['latin'] });

interface Props {
  children: ReactNode;
}

const RootLayout = ({ children }: Props): ReactNode => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalContextProvider>
          <Header>
            <Header.Center>
              <NavbarTop />
            </Header.Center>
          </Header>
          {children}
          <Modal />
        </ModalContextProvider>
      </body>
    </html>
  );
};

export default RootLayout;
