import clsx from 'clsx';
import { type Metadata } from 'next';
import { Inter } from 'next/font/google';
import { type ReactNode } from 'react';
import { Header, Modal, TopBar } from '@/components';
import { ModalProvider } from '@/providers';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const inter = Inter({ subsets: ['latin'] });

interface Props {
  children: ReactNode;
}

const RootLayout = ({ children }: Props): ReactNode => {
  const classNames: string = clsx(inter.className, 'bg-zinc-900 text-white');

  return (
    <html lang="en">
      <body className={classNames}>
        <ModalProvider>
          <Header>
            <Header.Center>
              <TopBar />
            </Header.Center>
          </Header>
          {children}
          <Modal />
        </ModalProvider>
      </body>
    </html>
  );
};

export default RootLayout;
