import { type Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import { Header, Modal, NavbarTop } from '@/components';
import { ModalProvider } from '@/providers';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const inter = Inter({ subsets: ['latin'] });

type Props = {
  children: ReactNode;
};

const RootLayout = ({ children }: Props): ReactNode => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalProvider>
          <Header>
            <Header.Center>
              <NavbarTop />
            </Header.Center>
          </Header>
          {children}
          <Modal />
        </ModalProvider>
      </body>
    </html>
  );
};

export default RootLayout;
